### ISSUE TITLE
Is there any way IFRAME can accept values from outside and pre-fill some of the fields?

### ISSUE THREAD

**Issue by manojgsequoia** [Finch-API/react-connect#79]
Hi Team,

Is there any way IFRAME can accept values from outside and pre-fill some of the fields?

 Like I want to pass username from my application to IFRAME and let the field in IFRAME prefilled with the value provided from outside?
 
Is this currently acheivable?

**Comment by M-Shehu** [comment]
Hey @manojgsequoia. This is currently not possible. However, we'll be sure to update you if we decide to include these fields as options you can pass into the SDK constructor in the future
