### ISSUE TITLE
Is it possible to only allow a specified list of providers when using the SDK?

### ISSUE THREAD

**Issue by charlie-ttt** [Finch-API/react-connect#81]
Is it possible to only show a specified list of providers when using the SDK (during provider selection)? For example, if I only want to support only Gusto and ADP Run providers, and want only these 2 option to show. 

Is this possible?

Thank you!

**Comment by diaswrd** [comment]
Hi @charlie-ttt, good question. Have you tried the `Integrations` tab in the top navigation bar of https://dashboard.tryfinch.com/? There you can enable/disable providers that will show during Connect in real-time.
 
<img width="1205" alt="Screenshot 2024-04-09 at 11 43 45 AM" src="https://github.com/Finch-API/react-connect/assets/800417/1f3b405b-eed8-4b78-a0ea-8f74c9e66a4a">

Hope that helps.

**Comment by charlie-ttt** [comment]
Thanks @diaswrd
